# Generated by Django 3.1 on 2020-08-09 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contactforwmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForwMessage',
            new_name='ContactFormMessage',
        ),
    ]
